// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: go-metrics-altering.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GaugeMetric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // metric name
	Value float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"` // metric value
}

func (x *GaugeMetric) Reset() {
	*x = GaugeMetric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_metrics_altering_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GaugeMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GaugeMetric) ProtoMessage() {}

func (x *GaugeMetric) ProtoReflect() protoreflect.Message {
	mi := &file_go_metrics_altering_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GaugeMetric.ProtoReflect.Descriptor instead.
func (*GaugeMetric) Descriptor() ([]byte, []int) {
	return file_go_metrics_altering_proto_rawDescGZIP(), []int{0}
}

func (x *GaugeMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GaugeMetric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AddGaugeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metric *GaugeMetric `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
}

func (x *AddGaugeRequest) Reset() {
	*x = AddGaugeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_metrics_altering_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGaugeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGaugeRequest) ProtoMessage() {}

func (x *AddGaugeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_metrics_altering_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGaugeRequest.ProtoReflect.Descriptor instead.
func (*AddGaugeRequest) Descriptor() ([]byte, []int) {
	return file_go_metrics_altering_proto_rawDescGZIP(), []int{1}
}

func (x *AddGaugeRequest) GetMetric() *GaugeMetric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type AddGaugeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // error
}

func (x *AddGaugeResponse) Reset() {
	*x = AddGaugeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_metrics_altering_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGaugeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGaugeResponse) ProtoMessage() {}

func (x *AddGaugeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_metrics_altering_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGaugeResponse.ProtoReflect.Descriptor instead.
func (*AddGaugeResponse) Descriptor() ([]byte, []int) {
	return file_go_metrics_altering_proto_rawDescGZIP(), []int{2}
}

func (x *AddGaugeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CounterMetric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`    // metric name
	Value int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // metric value
}

func (x *CounterMetric) Reset() {
	*x = CounterMetric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_metrics_altering_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounterMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterMetric) ProtoMessage() {}

func (x *CounterMetric) ProtoReflect() protoreflect.Message {
	mi := &file_go_metrics_altering_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterMetric.ProtoReflect.Descriptor instead.
func (*CounterMetric) Descriptor() ([]byte, []int) {
	return file_go_metrics_altering_proto_rawDescGZIP(), []int{3}
}

func (x *CounterMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CounterMetric) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AddCounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metric *CounterMetric `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
}

func (x *AddCounterRequest) Reset() {
	*x = AddCounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_metrics_altering_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCounterRequest) ProtoMessage() {}

func (x *AddCounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_metrics_altering_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCounterRequest.ProtoReflect.Descriptor instead.
func (*AddCounterRequest) Descriptor() ([]byte, []int) {
	return file_go_metrics_altering_proto_rawDescGZIP(), []int{4}
}

func (x *AddCounterRequest) GetMetric() *CounterMetric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type AddCounterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // error
}

func (x *AddCounterResponse) Reset() {
	*x = AddCounterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_metrics_altering_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCounterResponse) ProtoMessage() {}

func (x *AddCounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_metrics_altering_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCounterResponse.ProtoReflect.Descriptor instead.
func (*AddCounterResponse) Descriptor() ([]byte, []int) {
	return file_go_metrics_altering_proto_rawDescGZIP(), []int{5}
}

func (x *AddCounterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_go_metrics_altering_proto protoreflect.FileDescriptor

var file_go_metrics_altering_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x6f, 0x2d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2d, 0x61, 0x6c, 0x74,
	0x65, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x22, 0x37, 0x0a, 0x0b, 0x47, 0x61, 0x75, 0x67, 0x65, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3f, 0x0a,
	0x0f, 0x41, 0x64, 0x64, 0x47, 0x61, 0x75, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x61, 0x75, 0x67, 0x65,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x22, 0x28,
	0x0a, 0x10, 0x41, 0x64, 0x64, 0x47, 0x61, 0x75, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x39, 0x0a, 0x0d, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x43, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x22, 0x2a, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x32, 0x9d, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x12, 0x45, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x47, 0x61, 0x75, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x12, 0x18, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x41, 0x64, 0x64,
	0x47, 0x61, 0x75, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x61, 0x75, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x1a, 0x2e, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x6f, 0x2d, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x2d, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_go_metrics_altering_proto_rawDescOnce sync.Once
	file_go_metrics_altering_proto_rawDescData = file_go_metrics_altering_proto_rawDesc
)

func file_go_metrics_altering_proto_rawDescGZIP() []byte {
	file_go_metrics_altering_proto_rawDescOnce.Do(func() {
		file_go_metrics_altering_proto_rawDescData = protoimpl.X.CompressGZIP(file_go_metrics_altering_proto_rawDescData)
	})
	return file_go_metrics_altering_proto_rawDescData
}

var file_go_metrics_altering_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_go_metrics_altering_proto_goTypes = []any{
	(*GaugeMetric)(nil),        // 0: metrics.GaugeMetric
	(*AddGaugeRequest)(nil),    // 1: metrics.AddGaugeRequest
	(*AddGaugeResponse)(nil),   // 2: metrics.AddGaugeResponse
	(*CounterMetric)(nil),      // 3: metrics.CounterMetric
	(*AddCounterRequest)(nil),  // 4: metrics.AddCounterRequest
	(*AddCounterResponse)(nil), // 5: metrics.AddCounterResponse
}
var file_go_metrics_altering_proto_depIdxs = []int32{
	0, // 0: metrics.AddGaugeRequest.metric:type_name -> metrics.GaugeMetric
	3, // 1: metrics.AddCounterRequest.metric:type_name -> metrics.CounterMetric
	1, // 2: metrics.Metrics.AddGaugeMetric:input_type -> metrics.AddGaugeRequest
	4, // 3: metrics.Metrics.AddCounterMetric:input_type -> metrics.AddCounterRequest
	2, // 4: metrics.Metrics.AddGaugeMetric:output_type -> metrics.AddGaugeResponse
	5, // 5: metrics.Metrics.AddCounterMetric:output_type -> metrics.AddCounterResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_go_metrics_altering_proto_init() }
func file_go_metrics_altering_proto_init() {
	if File_go_metrics_altering_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_go_metrics_altering_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GaugeMetric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_metrics_altering_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddGaugeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_metrics_altering_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddGaugeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_metrics_altering_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CounterMetric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_metrics_altering_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AddCounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_metrics_altering_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AddCounterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_go_metrics_altering_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_metrics_altering_proto_goTypes,
		DependencyIndexes: file_go_metrics_altering_proto_depIdxs,
		MessageInfos:      file_go_metrics_altering_proto_msgTypes,
	}.Build()
	File_go_metrics_altering_proto = out.File
	file_go_metrics_altering_proto_rawDesc = nil
	file_go_metrics_altering_proto_goTypes = nil
	file_go_metrics_altering_proto_depIdxs = nil
}
